export const reducerCases = {
  SET_STATE: "SET_STATE",

  SET_FULLSCREEN_MODE: "SET_FULLSCREEN_MODE",

  SET_USER_INFO: "SET_USER_INFO",
  SET_NEW_USER: "SET_NEW_USER",
  SET_ALL_CONTACTS: "SET_ALL_CONTACTS",
  CHANGE_CURRENT_CHAT_USER: "CHANGE_CURRENT_CHAT_USER",

  SET_MESSAGES: "SET_MESSAGES",
  SET_UNREAD_MESSAGES: "SET_UNREAD_MESSAGES",
  SET_SOCKET: "SET_SOCKET",
  ADD_MESSAGE: "ADD_MESSAGE",
  MESSAGE_SEARCH_APPLIED: "SET_MESSAGE_SEARCH_APPLIED",
  SET_SEARCH_CONTACT_USERS: "SET_SEARCH_CONTACT_USERS",
  SET_SEARCH_ALL_CONTACT_USERS: "SET_SEARCH_ALL_CONTACT_USERS",

  SET_CONTACT_USERS: "SET_CONTACT_USERS",
  SET_ONLINE_USERS: "SET_ONLINE_USERS",

  SET_INCOMING_VOICE_CALL: "SET_INCOMING_VOICE_CALL",
  SET_INCOMING_VIDEO_CALL: "SET_INCOMING_VIDEO_CALL",
  SET_VOICE_CALL: "SET_VOICE_CALL",
  SET_VIDEO_CALL: "SET_VIDEO_CALL",
  SET_END_CALL: "SET_END_CALL",

  SET_ALL_USERS_STORIES: "SET_ALL_USERS_STORIES",

  SET_FETCHED_FEED: "SET_FETCHED_FEED",
  SET_ATTEMPTED_FEED: "SET_ATTEMPTED_FEED",

  SET_ALL_CONTACTS_CONNECTED: "SET_ALL_CONTACTS_CONNECTED",

};

export const asyncStoragePrefixes={
  CHAT_FROM_TO:"chatin_chat_history"
}